version: "3"
services:
    notebook:
        build:
            context: .
            args:
                CASE_STUDY_DIR: data/Haber-et-al_mouse-intestinal-epithelium
        image: sc-tutorial
        ports:
            - '8887:8887'
        command: [
            jupyter, notebook, --ip=0.0.0.0, --port=8887, --allow-root, --no-browser, --NotebookApp.token=admin
        ]
