name: sc-tutorial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.5
  - pandas==0.24.1
  - numpy==1.16.2
  - scipy==1.3.0
  - scikit-learn==0.20.2
  - cmake
  - jupyter
  - gsl
  - tzlocal
  - simplegeneric
  - natsort
  - h5py
  - tqdm
  - patsy
  - llvmlite
  - numba
  - networkx
  - joblib
  - numexpr
  - pytables
  - seaborn
  - statsmodels==0.10
  - python-igraph
  - louvain==0.6.1
  - r-base==3.5.1
  - r-essentials
  - r-rngtools
  - r-rgl
  - r-devtools
  - r-gam
  - r-rcolorbrewer
  - r-biocmanager
  - bioconductor-rhdf5lib
  - bioconductor-scran
  - bioconductor-mast
  - bioconductor-monocle
  - bioconductor-complexheatmap
  - bioconductor-slingshot
  - bioconductor-clusterexperiment
  - pip
  - pip:
    - scanpy==1.4.4
    - anndata==0.6.22
    - MulticoreTSNE
    - fa2
    - rpy2
    - gprofiler-official
    - git+https://github.com/flying-sheep/anndata2ri
